# Copyright (c) 2021 Marty Mills <daggerbot@gmail.com>
# This file is subject to the terms of the ISC license.
# See LICENSE.txt in the project directory for more information.

PKG_NAMES = libcap libcap-bin libcap-devel
PKG_VERSION = 2.48
PKG_RELEASE = 1.cellos
PKG_ARCH = any

DIST_SOURCES = \
	https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-${PKG_VERSION}.tar.gz
DIST_SHA256SUMS = \
	632eabd82089f8f9744e4e965b327a4f518c3c512cebe7d4a7ed844da9c0c2b5

include ../../mk/pkg.mk
