# Copyright (c) 2021 Marty Mills <daggerbot@gmail.com>
# This file is subject to the terms of the ISC license.
# See LICENSE.txt in the project directory for more information.

PKG_NAMES = filesystem
PKG_VERSION = 0.1
PKG_RELEASE = 1.cellos
PKG_ARCH = any
PKG_OPTIONS = KeepEmptyDirs

include ../../mk/pkg.mk
