# Copyright (c) 2021 Marty Mills <daggerbot@gmail.com>
# This file is subject to the terms of the ISC license.
# See LICENSE.txt in the project directory for more information.

PKG_NAMES = zstd libzstd libzstd-devel
PKG_VERSION = 1.4.8
PKG_RELEASE = 1.cellos
PKG_ARCH = any

DIST_SOURCES = \
	https://github.com/facebook/zstd/releases/download/v${PKG_VERSION}/zstd-${PKG_VERSION}.tar.zst
DIST_SHA256SUMS = \
	c7ea10e20dd61b457220455e3cf553069987b968b7c63d1b9d46acbdb45623eb

include ../../mk/pkg.mk
