# Copyright (c) 2021 Marty Mills <daggerbot@gmail.com>
# This file is subject to the terms of the ISC license.
# See LICENSE.txt in the project directory for more information.

PKG_NAMES = ex
PKG_VERSION = 050325
PKG_RELEASE = 1.cellos
PKG_ARCH = any
PKG_OPTIONS = KeepEmptyDirs

DIST_SOURCES = \
	https://phoenixnap.dl.sourceforge.net/project/ex-vi/ex-vi/${PKG_VERSION}/ex-${PKG_VERSION}.tar.bz2
DIST_SHA256SUMS = \
	da4be7cf67e94572463b19e56850aa36dc4e39eb0d933d3688fe8574bb632409

include ../../mk/pkg.mk
